include: package:very_good_analysis/analysis_options.yaml
analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    -  "**/injection.iconfig.dart"
  errors:
    missing_required_param: error
    missing_return: error
    must_be_immutable: error
linter:
  rules:
    public_member_api_docs: false
    prefer_const_constructors: false
    lines_longer_than_80_chars: false
    non_constant_identifier_names: false
    constant_identifier_names: false
    sort_constructors_first: false
    directives_ordering: false